### ISSUE TITLE
DCF and evaluation issue

### ISSUE THREAD

**Issue by sajjadafridi** [xzenglab/DCF#1]
In the script **noval_DCF.m** a function named **mysdae_worker.m** which is missing in the current repository. I search it on the GitHub and found from another repository. The script works fine at training phase. but when executing the **noval_eval.m** script, recall function is missing. My question is, is there any custom recall function? 
I want to evaluate on the data set but I could not find any recall script, and function.
Please help me to sort out this..

**Comment by xzenglab** [comment]
sorry, we forget to upload the recall function, and we have fixed this problem. If any question, please contact us for solution.

**Comment by sajjadafridi** [comment]
Sir one more question, I did not find my_sdae.m file. I searched it and
found from another repositiry. I run it after fixing some issue but not
sure about the correctness of tge output score index file.
Thanks for your help.

**Comment by sajjadafridi** [comment]
#Thank for your response.

**Comment by sajjadafridi** [comment]
Dear the **sdae_worker** function used in the **my_sdae.m** script is also missing in the repository.

**Comment by sajjadafridi** [comment]
Thanks again.@xzenglab

**Comment by xzenglab** [comment]
sorry, I'm busy this days. I test the whole file and upload some new files to make our codes can be run successfully. The readme is also update for your better understanding.
